local tween_escala
local tween_mover
local tween_tint

function tween_tint(self)
	go.animate("#sprite", "tint.x", go.PLAYBACK_ONCE_PINGPONG, 0.0, go.EASING_INOUTSINE, 1.5, 0 , tween_mover)
end

function tween_escala(self)
	go.animate(".", "scale", go.PLAYBACK_ONCE_PINGPONG, 2, go.EASING_OUTINEXPO, 3, 1, tween_tint)
end

function tween_mover(self)
	local to = vmath.vector3(-200,0, 0) -- <1>
	local pos = go.get_position()
	go.animate(".", "position", go.PLAYBACK_ONCE_PINGPONG,  pos + to, go.EASING_INOUTSINE, 4, 1, tween_escala)
end

function init(self)
	tween_mover(self)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function late_update(self, dt)
	-- This function is called at the end of update cycle but before render
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
