function init(self)
	msg.post(".", "acquire_input_focus")
	self. dir = vmath.vector3()
	self.velocidad = 100
	self.vidas = 3
	self.mp = 6
	self.animacion_actual = hash("correr_arriba")
	msg.post("/GUI#HUD", "iniciar_ui", {vidas = self.vidas, mana = self.mp})
	sprite.play_flipbook("#sprite", self.animacion_actual)
	self.invulnerable = false
end

function update(self, dt)

	local animacion = nil
	
	if self.dir.y > 0 then
		animacion = hash("correr_arriba")
	elseif self.dir.y < 0 then
		animacion = hash("correr_abajo")
	elseif self.dir.x > 0 then
		animacion = hash("correr_derecha")
	elseif self.dir.x < 0 then
		animacion = hash("correr_izquierda")
	else
		animacion = hash("jugador1")
	end

	if animacion and animacion ~= self.animacion_actual then
		sprite.play_flipbook("#sprite", animacion)
		self.animacion_actual = animacion
	end
	
	if vmath.length(self.dir) > 0 then
		local pos = go.get_position()
		pos = pos + vmath.normalize(self.dir) * self.velocidad * dt
		go.set_position(pos)
		self.dir = vmath.vector3()
	end
end

function on_message(self, message_id, message, sender)
	if self.invulnerable then
		return
	end
	
	if message_id == hash("trigger_response") and message.enter then
		--go.delete(message.other_id)
		self.vidas =  self.vidas - 1
		self.invulnerable = true
		go.animate("#sprite", "tint", go.PLAYBACK_LOOP_PINGPONG, vmath.vector4(1, 0, 0, 1), go.EASING_LINEAR, 0.1)

		timer.delay(5, false, function() 
			go.cancel_animations("#sprite", "tint")	
			go.set("#sprite", "tint", vmath.vector4(1, 1, 1, 1))
			self.invulnerable = false
		end)	
		
		if self.vidas > -1 then
			msg.post("/GUI#HUD", "take_damage", {vidas = self.vidas})
		end
		
	end
end

function on_input(self, action_id, action)
	if action_id == hash("arriba") then self.dir.y = 1
	elseif action_id == hash("abajo") then self.dir.y = -1
	elseif action_id == hash("izquierda") then self.dir.x = -1
	elseif action_id == hash("derecha") then self.dir.x = 1
	end
end

