function init(self)
	msg.post(".", "acquire_input_focus")
	self. dir = vmath.vector3()
	self.velocidad = 100
	self.vidas = 3
	self.mp = 6
	self.animacion_actual = hash("correr_arriba")
	msg.post("/GUI#HUD", "iniciar_ui", {vidas = self.vidas, mana = self.mp})
	sprite.play_flipbook("#sprite", self.animacion_actual)
	self.invulnerable = false
	self.correction = vmath.vector3()
	self.direccion_mirada = vmath.vector3(0, 1, 0)
end

function update(self, dt)

	local animacion = hash("jugador1")
	
	if self.dir.y > 0 then
		animacion = hash("correr_arriba")
	elseif self.dir.y < 0 then
		animacion = hash("correr_abajo")
	elseif self.dir.x > 0 then
		animacion = hash("correr_derecha")
	elseif self.dir.x < 0 then
		animacion = hash("correr_izquierda")
	end

	if animacion and animacion ~= self.animacion_actual then
		sprite.play_flipbook("#sprite", animacion)
		self.animacion_actual = animacion
	end
	
	if vmath.length(self.dir) > 0 then
		self.direccion_mirada = vmath.normalize(self.dir)
		
		local pos = go.get_position()
		pos = pos + vmath.normalize(self.dir) * self.velocidad * dt
		go.set_position(pos)
		
		self.dir = vmath.vector3()
		self.correction = vmath.vector3()
	end
end

function on_message(self, message_id, message, sender)
	
	if message_id == hash("trigger_response") and message.enter then
		--go.delete(message.other_id)
		self.vidas =  self.vidas - 1
		self.invulnerable = true
		go.animate("#sprite", "tint", go.PLAYBACK_LOOP_PINGPONG, vmath.vector4(1, 0, 0, 1), go.EASING_LINEAR, 0.1)

		timer.delay(5, false, function() 
			go.cancel_animations("#sprite", "tint")	
			go.set("#sprite", "tint", vmath.vector4(1, 1, 1, 1))
			self.invulnerable = false
		end)	
		
		if self.vidas > -1 then
			msg.post("/GUI#HUD", "take_damage", {vidas = self.vidas})
		end
		
	end

	if message_id == hash("contact_point_response") then
		print("KIMEATIC")
		--local newpos = go.get_position() + message.normal * message.distance
		--go.set_position(newpos)
		if message.distance > 0 then
			-- First, project the accumulated correction onto
			-- the penetration vector
			local proj = vmath.project(self.correction, message.normal * message.distance)
			if proj < 1 then
				-- Only care for projections that does not overshoot.
				local comp = (message.distance - message.distance * proj) * message.normal
				-- Apply compensation
				go.set_position(go.get_position() + comp)
				-- Accumulate correction done
				self.correction = self.correction + comp
			end
		end
	end
end

function on_input(self, action_id, action)
	if action_id == hash("arriba") then self.dir.y = 1
	elseif action_id == hash("abajo") then self.dir.y = -1
	elseif action_id == hash("izquierda") then self.dir.x = -1
	elseif action_id == hash("derecha") then self.dir.x = 1
	elseif action_id == hash("ataque") and action.pressed then
		print("ATACAR")

		local posicion_spawn = go.get_position()
		local margen_separacion = 16
		posicion_spawn = posicion_spawn + (self.direccion_mirada * margen_separacion)
		posicion_spawn.z = 0.6
		
		local propiedades = { direccion = self.direccion_mirada }
		local id_del_kunai = factory.create("#kunai_factory", posicion_spawn, nil, propiedades)
		print("El factory generó el objeto con el ID:", id_del_kunai)
	end
end

