go.property("direccion", vmath.vector3(1, 0, 0))
go.property("velocidad", 20)

function init(self)
	if vmath.length(self.direccion) > 0 then
		self.direccion = vmath.normalize(self.direccion)
	end
end

function update(self, dt)
	local pos = go.get_position()
	pos = pos + self.direccion * self.velocidad * dt
	go.set_position(pos)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") or message_id == hash("contact_point_response") then
		go.delete()
	end
end

